FROM opensourcepolicycenter/tornado-base:latest

USER root

RUN mkdir /home/api
COPY ./api /home/api/
WORKDIR /home/api
RUN pip install -e .
WORKDIR /home/api/api

ENV HOST 0.0.0.0
ENV PORT 8888

# expose the app port
EXPOSE 80
EXPOSE 8888

ENV REDIS_ADDRESS redis://redis:6379/0

# run the app server
CMD ["python", "-u", "cluster_api.py"]
