FROM opensourcepolicycenter/tornado-base:latest

USER root

RUN pip install falcon

RUN mkdir /home/mock-app
COPY mock_pb.py /home/mock-app/
WORKDIR /home/mock-app

ENV PYTHONUNBUFFERED TRUE
ENV HOST 0.0.0.0
ENV PORT 8000

# expose the app port
EXPOSE 80
EXPOSE 8000

# run the app server
CMD ["gunicorn", "--bind", "0.0.0.0:8000", "mock_pb:api"]
