version: '3'
services:
  tornado:
    image: opensourcepolicycenter/tornado:redis-0
    ports:
      - 8888:8888
    environment:
      - PBRAIN_SCHEDULER_ADDRESS=scheduler:8786
    depends_on:
      - redis
      - scheduler
  redis:
    image: redis
  scheduler:
    image: opensourcepolicycenter/dask
    ports:
      - "8786:8786"
      - "8787:8787"
    command: ["dask-scheduler"]
    depends_on:
      - worker
  worker:
    image: opensourcepolicycenter/dask
    hostname: dask-worker
    command: ["dask-worker scheduler:8786"]
