apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "pbrain.fullname" . }}-worker
  labels:
    app: {{ template "pbrain.name" . }}
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: {{ template "pbrain.chart" . }}
    component: worker
spec:
  replicas: {{ .Values.worker.replicas }}
  selector:
    matchLabels:
      app: {{ template "pbrain.name" . }}
      release: {{ .Release.Name | quote }}
      component: worker
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ template "pbrain.name" . }}
        release: {{ .Release.Name | quote }}
        component: worker
    spec:
      containers:
        - name: {{ template "pbrain.fullname" . }}-worker
          image: "{{ .Values.worker.image.repository }}:{{ .Values.worker.image.tag }}"
          imagePullPolicy: {{ .Values.worker.image.pullPolicy }}
          args:
            - dask-worker
            - {{ template "pbrain.fullname" . }}-scheduler:{{ .Values.scheduler.servicePort }}
          {{- if .Values.worker.limits }}
            - --nthreads
            - {{ default .Values.worker.limits.cpu .Values.workers.default_resources.cpu | quote }}
            - --memory-limit
            - {{ default .Values.worker.limits.memory .Values.workers.default_resources.memory | quote }}
          {{- end }}
            - --no-bokeh
          ports:
            - containerPort: 8789
          resources:
{{ toYaml .Values.worker.resources | indent 12 }}
          env:
{{ toYaml .Values.worker.env | indent 12 }}
